/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_allenliu_ffmepgdemo_FFmpegNative */

#ifndef _Included_com_allenliu_ffmepgdemo_FFmpegNative
#define _Included_com_allenliu_ffmepgdemo_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_allenliu_ffmepgdemo_FFmpegNative
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allenliu_ffmepgdemo_FFmpegNative_helloJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_allenliu_ffmepgdemo_FFmpegNative
 * Method:    helloFFMPEG
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_allenliu_ffmepgdemo_FFmpegNative_helloFFMPEG
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
